// Listado completo de países (ISO 3166-1) en español.
// El `value` es el nombre en español porque las columnas `pais` / `nacionalidad` /
// `pais_documento` guardan texto libre desde siempre.
// `keywords` permite encontrar el país por nombres alternativos o de uso común
// (ej. "Holanda" -> Países Bajos, "EEUU" -> Estados Unidos).

export interface PaisOption {
  label: string
  value: string
  keywords?: string[]
}

// Países usados con más frecuencia por la comunidad; se muestran primero.
const DESTACADOS = [
  'Argentina',
  'Bolivia',
  'Brasil',
  'Chile',
  'Colombia',
  'España',
  'Italia',
  'México',
  'Paraguay',
  'Perú',
  'Uruguay',
]

const ALIAS: Record<string, string[]> = {
  Alemania: ['Deutschland', 'Germany'],
  'Arabia Saudí': ['Arabia Saudita'],
  Bangladés: ['Bangladesh'],
  Baréin: ['Bahrein', 'Bahrain'],
  Bielorrusia: ['Belarus'],
  Brasil: ['Brazil'],
  Brunéi: ['Brunei'],
  Camboya: ['Cambodia'],
  Catar: ['Qatar'],
  Chequia: ['República Checa', 'Republica Checa', 'Czechia'],
  'Ciudad del Vaticano': ['Vaticano', 'Santa Sede'],
  'Corea del Sur': ['Korea'],
  'Costa de Marfil': ["Côte d'Ivoire", 'Cote d Ivoire', 'Ivory Coast'],
  Croacia: ['Croatia'],
  'Emiratos Árabes Unidos': ['Dubai', 'Abu Dabi', 'UAE'],
  Esuatini: ['Suazilandia', 'Swazilandia', 'Eswatini'],
  'Estados Unidos': ['EEUU', 'EE UU', 'USA', 'United States', 'Norteamérica'],
  Filipinas: ['Philippines'],
  Fiyi: ['Fiji'],
  Grecia: ['Greece'],
  Irak: ['Iraq'],
  Irlanda: ['Ireland', 'Eire'],
  'Islas Malvinas': ['Falkland'],
  Japón: ['Japan'],
  Kazajistán: ['Kazajstán', 'Kazakhstan'],
  Kirguistán: ['Kirguizistán', 'Kyrgyzstan'],
  Malaui: ['Malawi'],
  Mali: ['Malí'],
  'Macedonia del Norte': ['Macedonia'],
  Moldavia: ['Moldova'],
  'Myanmar (Birmania)': ['Birmania', 'Myanmar'],
  'Países Bajos': ['Holanda', 'Netherlands', 'Nederland'],
  Palaos: ['Palau'],
  'Reino Unido': ['Inglaterra', 'Gran Bretaña', 'UK', 'Escocia', 'Gales'],
  'República Dominicana': ['Santo Domingo'],
  Rumanía: ['Rumania', 'Romania'],
  Rusia: ['Russia'],
  Singapur: ['Singapore'],
  Suecia: ['Sweden'],
  Suiza: ['Switzerland', 'Schweiz', 'Svizzera'],
  Surinam: ['Suriname'],
  Tailandia: ['Thailand'],
  'Territorios Palestinos': ['Palestina'],
  'Timor-Leste': ['Timor Oriental'],
  Turquía: ['Turkey', 'Türkiye'],
  Vietnam: ['Viet Nam'],
  Yibuti: ['Djibouti'],
  Zimbabue: ['Zimbabwe'],
}

const TODOS = [
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Anguila',
  'Antigua y Barbuda',
  'Arabia Saudí',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Bangladés',
  'Barbados',
  'Baréin',
  'Bélgica',
  'Belice',
  'Benín',
  'Bermudas',
  'Bielorrusia',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Bután',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'Catar',
  'Chad',
  'Chequia',
  'Chile',
  'China',
  'Chipre',
  'Ciudad del Vaticano',
  'Colombia',
  'Comoras',
  'Congo',
  'Corea del Norte',
  'Corea del Sur',
  'Costa de Marfil',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Curazao',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Eritrea',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Esuatini',
  'Etiopía',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Gabón',
  'Gambia',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Granada',
  'Grecia',
  'Groenlandia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guayana Francesa',
  'Guernesey',
  'Guinea',
  'Guinea Ecuatorial',
  'Guinea-Bisáu',
  'Guyana',
  'Haití',
  'Honduras',
  'Hong Kong',
  'Hungría',
  'India',
  'Indonesia',
  'Irak',
  'Irán',
  'Irlanda',
  'Isla de Man',
  'Islandia',
  'Islas Caimán',
  'Islas Cook',
  'Islas Feroe',
  'Islas Malvinas',
  'Islas Marianas del Norte',
  'Islas Marshall',
  'Islas Salomón',
  'Islas Turcas y Caicos',
  'Islas Vírgenes Británicas',
  'Islas Vírgenes de EE. UU.',
  'Israel',
  'Italia',
  'Jamaica',
  'Japón',
  'Jersey',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letonia',
  'Líbano',
  'Liberia',
  'Libia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macao',
  'Macedonia del Norte',
  'Madagascar',
  'Malasia',
  'Malaui',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayotte',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Mozambique',
  'Myanmar (Birmania)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Niue',
  'Noruega',
  'Nueva Caledonia',
  'Nueva Zelanda',
  'Omán',
  'Países Bajos',
  'Pakistán',
  'Palaos',
  'Panamá',
  'Papúa Nueva Guinea',
  'Paraguay',
  'Perú',
  'Polinesia Francesa',
  'Polonia',
  'Portugal',
  'Puerto Rico',
  'Reino Unido',
  'República Centroafricana',
  'República Democrática del Congo',
  'República Dominicana',
  'Reunión',
  'Ruanda',
  'Rumanía',
  'Rusia',
  'Sáhara Occidental',
  'Samoa',
  'Samoa Americana',
  'San Bartolomé',
  'San Cristóbal y Nieves',
  'San Marino',
  'San Martín',
  'San Pedro y Miquelón',
  'San Vicente y las Granadinas',
  'Santa Elena',
  'Santa Lucía',
  'Santo Tomé y Príncipe',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leona',
  'Singapur',
  'Sint Maarten',
  'Siria',
  'Somalia',
  'Sri Lanka',
  'Sudáfrica',
  'Sudán',
  'Sudán del Sur',
  'Suecia',
  'Suiza',
  'Surinam',
  'Tailandia',
  'Taiwán',
  'Tanzania',
  'Tayikistán',
  'Territorios Palestinos',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad y Tobago',
  'Túnez',
  'Turkmenistán',
  'Turquía',
  'Tuvalu',
  'Ucrania',
  'Uganda',
  'Uruguay',
  'Uzbekistán',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Wallis y Futuna',
  'Yemen',
  'Yibuti',
  'Zambia',
  'Zimbabue',
]

function toOption(nombre: string): PaisOption {
  return { label: nombre, value: nombre, keywords: ALIAS[nombre] }
}

export const PAISES: PaisOption[] = [
  ...DESTACADOS.map(toOption),
  ...TODOS.filter((p) => !DESTACADOS.includes(p)).map(toOption),
]

export const NOMBRES_PAISES = TODOS
